nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.4.1.cjs

packageExtensions:
  pdfjs-dist@*:
    dependencies:
      "web-streams-polyfill": "^3.0.3"
  mammoth@*:
    dependencies:
      "process": "^0.11.10"

nmHoistingLimits: workspaces